# Generated by Django 6.0 on 2026-08-30 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('disputed_orders', models.IntegerField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0.0)),
                ('avg_delay_mins', models.FloatField(default=0.0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('delayed_deliveries', models.IntegerField(default=0)),
                ('total_disruptions', models.IntegerField(default=0)),
                ('agent_resolved_disruptions', models.IntegerField(default=0)),
                ('human_escalated_disruptions', models.IntegerField(default=0)),
                ('avg_agent_response_time_s', models.FloatField(default=0.0)),
                ('avg_delay_saved_mins', models.FloatField(default=0.0)),
                ('distributor_scores_json', models.JSONField(blank=True, default=dict)),
                ('memory_queries_total', models.IntegerField(default=0)),
                ('memory_hit_rate', models.FloatField(default=0.0)),
                ('memory_improvement_rate', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
