# Generated by Django 5.2 on 2026-08-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fleet_size', models.IntegerField(default=10)),
                ('reliability_score', models.FloatField(default=0.92)),
                ('status', models.CharField(default='AVAILABLE', max_length=50)),
                ('contact_phone', models.CharField(default='+91 9898989898', max_length=20)),
                ('vehicle_type', models.CharField(default='Heavy-Duty Refrigerated Truck', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity_tons', models.FloatField(default=5.0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('DISRUPTED', 'Disrupted'), ('REROUTED', 'Rerouted / Reassigned'), ('DELIVERED', 'Delivered')], default='IN_TRANSIT', max_length=50)),
                ('original_eta', models.DateTimeField()),
                ('current_eta', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.transporter')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_orders', to='orders.warehouselocation')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_orders', to='orders.warehouselocation')),
            ],
        ),
    ]
