# Generated by Django 5.2 on 2026-08-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisruptionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_type', models.CharField(choices=[('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('ROAD_BLOCKADE', 'Road Blockade'), ('ORDER_MODIFICATION', 'Order Modification')], default='ROAD_BLOCKADE', max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(default=18.5204)),
                ('longitude', models.FloatField(default=73.8567)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('PROCESSING', 'Processing (Multi-Agent Engine)'), ('RESOLVED', 'Resolved & Validated'), ('REJECTED', 'Rejected')], default='REPORTED', max_length=50)),
                ('detour_km', models.FloatField(default=0.0)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.transporter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disruptions', to='orders.order')),
            ],
        ),
    ]
