# Generated by Django 6.0 on 2026-08-30 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('quantity_unit', models.CharField(default='tons', max_length=50)),
                ('weight_kg', models.FloatField(default=1000.0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('disrupted', 'Disrupted'), ('rerouted', 'Rerouted'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='created', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('revised_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('actual_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery_url', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('agent_handled', models.BooleanField(default=False)),
                ('disruption_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_type', models.CharField(choices=[('original', 'Original'), ('rerouted', 'Rerouted'), ('manual', 'Manual')], default='original', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('estimated_duration_mins', models.FloatField(default=0.0)),
                ('actual_duration_mins', models.FloatField(blank=True, default=0.0, null=True)),
                ('delay_vs_original_mins', models.FloatField(default=0.0)),
                ('agent_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(default=1)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reached', 'Reached'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('distance_from_prev_km', models.FloatField(default=0.0)),
                ('duration_from_prev_mins', models.FloatField(default=0.0)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
