# Generated by Django 6.0 on 2026-08-30 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('planner', 'Planner Agent (L1)'), ('route_executor', 'Route Executor Agent (L2)'), ('resource_executor', 'Resource Executor Agent (L2)'), ('critic', 'Critic Agent (L3)')], max_length=30)),
                ('action_type', models.CharField(choices=[('task_decomposition', 'Task Decomposition'), ('memory_query', 'Memory Query'), ('route_proposal', 'Route Proposal'), ('resource_proposal', 'Resource Proposal'), ('critic_approval', 'Critic Approval'), ('critic_rejection', 'Critic Rejection'), ('plan_executed', 'Plan Executed'), ('memory_write', 'Memory Write'), ('escalation', 'Escalation')], max_length=30)),
                ('input_summary', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True, null=True)),
                ('revision_round', models.IntegerField(default=0)),
                ('critic_feedback', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('transporter_assigned', 'Transporter Assigned'), ('order_picked_up', 'Order Picked Up'), ('waypoint_reached', 'Waypoint Reached'), ('disruption_reported', 'Disruption Reported'), ('agent_rerouted', 'Agent Rerouted'), ('transporter_reassigned', 'Transporter Reassigned'), ('order_delivered', 'Order Delivered'), ('delivery_confirmed', 'Delivery Confirmed'), ('dispute_raised', 'Dispute Raised'), ('order_cancelled', 'Order Cancelled'), ('agent_escalated', 'Agent Escalated')], max_length=50)),
                ('triggered_by_agent', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisruptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disruption_type', models.CharField(choices=[('vehicle_breakdown', 'Vehicle Breakdown'), ('road_block', 'Road Blockade'), ('accident', 'Accident'), ('weather', 'Severe Weather'), ('order_modification', 'Order Modification'), ('transporter_unwell', 'Transporter Unwell'), ('other', 'Other Disruption')], default='road_block', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_latitude', models.FloatField(default=0.0)),
                ('location_longitude', models.FloatField(default=0.0)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remaining_waypoints_json', models.JSONField(blank=True, default=list)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('agent_response_time_s', models.FloatField(default=0.0)),
                ('memory_hits', models.IntegerField(default=0)),
                ('outcome_delay_mins', models.FloatField(default=0.0)),
                ('outcome_success', models.BooleanField(default=True)),
                ('chroma_memory_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
