# Generated by Django 6.0 on 2026-08-30 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disruptions', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disruptionevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disruption_events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='disruptionevent',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_disruptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentdecisionlog',
            name='disruption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='disruptions.disruptionevent'),
        ),
    ]
