# Generated by Django 5.2 on 2026-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('TRANSPORTER', 'Transporter'), ('RETAILER', 'Retailer')], default='MANUFACTURER', max_length=20)),
                ('organization_name', models.CharField(default='SupplyChain Corp', max_length=255)),
                ('email', models.EmailField(default='user@supplychain.ai', max_length=254)),
                ('phone', models.CharField(default='+91 9876543210', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
