# Generated by Django 6.0 on 2026-08-30 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disruptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveMemoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chroma_vector_id', models.CharField(max_length=255, unique=True)),
                ('embedded_text', models.TextField()),
                ('disruption_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_approach', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('escalated', 'Escalated')], default='success', max_length=20)),
                ('delay_mins', models.FloatField(default=0.0)),
                ('agent_confidence', models.FloatField(default=0.9)),
                ('retrieval_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disruption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_record', to='disruptions.disruptionevent')),
            ],
        ),
    ]
